--Q1 What is the total revenue generated by male vs.female customers? for demographisc
select gender,
sum(purchase_amount) as revenue
from customer
group by gender
--Q2 Which customer used a discount but still spent more than the averange purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)
--Q3 Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
    item_purchased, 
    ROUND( AVG(review_rating),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;
--Q4 Compare the average Purchase Amounts between Standart and Express Shiping
SELECT shipping_type,
CAST(AVG(purchase_amount) AS DECIMAL(10,2)) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;
--Q5 Do subscribed customers spend more ? Compare avegage spend and total revenue between subscribes and non-subcribes.
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
CAST(AVG(purchase_amount) AS DECIMAL(10,2)) AS avg_spend,
CAST(SUM(purchase_amount) AS DECIMAL(10,2)) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;
--Q6 Which 5 products have the highest % of purchases with discounts applied?
SELECT TOP 5
    item_purchased,
    CAST(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*) AS DECIMAL(10,2)
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;
--Q7 Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
--and show the count of each segment
with customer_type as(
  select customer_id, previous_purchases,
  CASE
     WHEN previous_purchases = 1 THEN 'New'
	 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	 ELSE 'Loyal'
	 END AS customer_segment
from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8 What are the top 3 most purchased productc within each category? 
-- Counts how many times a product has been purchased in each category.
--Ranking products in each category separately.
--Selects the TOP 3 products in each category.

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;
--Q9 Are customers who are repeat buyers( more than 5 previous purchases) also likly to subscribe?
select  subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status
--Q10 What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;